USE ecommerce;

INSERT INTO
	Categorie (idCategoria)
VALUES
	('Smartphone'),
	('Laptop'),
	('Headphones'),
	('Smartwatch');

INSERT INTO
	Prodotti (idProdotto, nome, descS, descL, prezzo, quantita, idCategoria)
VALUES
	(NULL, 'Iphone X', 'Super Retina HD, Multi‑Touch OLED, Display, 3D Touch', 'Apple iPhone X è uno smartphone iOS con caratteristiche all\'avanguardia che lo rendono una scelta eccellente per ogni tipo di utilizzo. Dispone di un grande display da 5.8 pollici e di una risoluzione da 2436x1125 pixel, fra le più elevate attualmente in circolazione. Le funzionalità offerte da questo Apple iPhone X sono innumerevoli e al top di gamma. A cominciare dal modulo LTE 4G che permette un trasferimento dati e una navigazione in internet eccellente, passando per la connettività Wi-fi e il GPS.\r\nFotocamera da 12 megapixel. Lo spessore di 7.7mm è veramente contenuto e rende questo Apple iPhone X ancora più spettacolare.', '399.99', '15', 'Smartphone'),
	(NULL, 'Lenovo laptop thinkpad t15g', 'Processore Intel Core i7-10875H, Windows 10 Pro 64, Unità SSD da 512 GB', 'Creato per utenti esperti\r\nIl notebook ThinkPad T15g sfrutta la potenza dei processori Intel® Core™ o Xeon® fino alla decima generazione con un massimo di 8 core per soddisfare le esigenze degli utenti con i flussi di lavoro più complessi. Le schede grafiche NVIDIA® GeForce RTX™ opzionali offrono potenza grafica mobile senza confronti. \r\n\r\nNon solo potenza\r\nIl flusso d\'aria e la saturazione termica ottimizzati di ThinkPad T15g garantiscono velocità ed efficienza al dispositivo.', '2519', '3', 'Laptop'),
	(NULL, 'Samsung Galaxy Fold', 'Smartphone con schermo pieghevole', 'Design innovativo e rivoluzionario. Display Infinity Flex per un’esperienza senza precedenti. App Continuity e Multitasking Avanzato per avere più libertà e divertimento. Performance superiori per la massima versatilità. 12GB RAM. 512GB SSD (di cui il 10% dedicato al sistema). Colorazione: cosmos Black', '1256.50', '100', 'Smartphone'),
	(NULL, 'Lenovo Flex 5', 'Lenovo IdeaPad Flex 5 Notebook Convertibile, Display 14" Full HD IPS Touch, Processore AMD Ryzen 3 5300U, 256 GB SSD, RAM 8 GB, Lenovo Digital Pen, Windows 10 Home in modalità S, Graphite Grey', 'Display touch 14" Full HD con risoluzione 1920x1080 e pannello IPS, 250nits; con questo schermo godrai di immagini dettagliate e nitide da ogni angolazione. Processore AMD Ryzen 3 5300U (4C / 8T, 2.6 / 3.8GHz, 2MB L2 / 4MB L3); con questo processore si hanno ottime prestazioni a consumi ridotti. Storage da 256GB SSD M.2 2242 PCIe 3.0x4 NVMe, per avere tutto lo spazio necessario dove archiviare i tuoi documenti di lavoro in velocità e sicurezza. 8GB Soldered DDR4-3200; una RAM ad alte prestazioni. Scheda grafica: AMD Radeon Graphics. Progettato per piegarsi a 360° trasformandosi da notebook a tablet, IdeaPad Flex 5 ti offre la flessibilità necessaria per usarlo in diverse modalità, in base alle tue esigenze.. Lenovo Digital Pen inclusa nella confezione. Leggerissimo e super sottile, con un peso di 1.5 kg e spessore di 1,79 cm; materiale: PC + ABS (parte superiore), PC + GF (parte inferiore).', '665.66', '70', 'Laptop'),
	(NULL, 'Apple AirPods Pro', 'Apple AirPods Pro: cuffie auricolari wireless bianchi', 'Cancellazione attiva del rumore per immergerti nel suono. Modalità trasparenza per ascoltare il mondo intorno a te. Affusolati cuscinetti in tre taglie, realizzati in morbido silicone, per un comfort su misura. Resistenti all\'acqua e al sudore. Equalizzazione adattiva che regola automaticamente la musica in base alla forma del tuo orecchio. Setup semplicissimo su tutti i dispositivi apple. Attivazione rapida di siri con il comando “ehi siri”. Custodia di ricarica wireless per oltre 24 ore di autonomia.', '149.99', '20', 'Headphones'),
	(NULL, 'Samsung Galaxy A52', 'Samsung Galaxy A52 Smartphone, Display Infinity-O FHD+ da 6,5 pollici, 6 GB RAM e 128 GB di memoria interna espandibile, Batteria 4.500 mAh e ricarica Ultra-Rapida Black', 'Display 6,5 pollici Infinity-O: schermo con tecnologia FHD+ Super AMOLED. Splendido design: smartphone android dalle curve sottili e il design aerodinamico. L’alloggiamento ridotto della fotocamera si fonde alla perfezione con la finitura opaca, donando al telefono un look emblematico. Sistema multicamera: foto di qualità superiore grazie alla fotocamera principale da 64MP che realizza scatti chiari e nitidi. Batteria 4.500mAh:¹⁶ dedica più tempo a ciò che ami grazie alla batteria di lunga durata dei telefoni cellulari Samsung, e ricaricati velocemente con 25W di ricarica Ultra-Rapida adattiva. Vivi le tue giornate all’insegna del multitasking grazie ad una potenza di elaborazione fino a 6 GB di RAM e a 128 GB di memoria interna.', '379.99', '500', 'Smartphone'),
	(NULL, 'Fitbit Charge 4', 'Fitbit Charge 4: fitness tracker con GPS integrato, rilevazione del nuoto e fino a 7 giorni di durata della batteria', 'Batteria fino a 7 giorni o 5 ore utilizzando il GPS. Compatibilità: Compatibile con iOS 12.2 o successive & Android OS 7.0 o successivi. GPS integrato: lascia il telefono a casa e goditi l\'aria aperta; con il GPS integrato potrai tenere d\'occhio ritmo e distanza sul tracker e scoprire sull\'app una mappa di intensità dell\'allenamento che ti mostra il percorso e i tuoi sforzi al termine dell\'esercizio. Minuti in zona attiva: questa funzione ti avvisa della zona cardio in cui ti trovi per aiutarti a scoprire se ti stai impegnando abbastanza per raggiungere i tuoi obiettivi. Fasi e punteggio del sonno: charge 4 traccia il tempo che trascorri nelle fasi di sonno leggero, profondo e rem, e calcola un punteggio del sonno notturno nell\'app fitbit, così puoi comprendere la qualità del tuo riposo e scoprire come dormire meglio. App e notifiche: resta connesso con avvisi di chiamata, calendario e delle app smartphone, notifiche di messaggi, e pratiche app come meteo e timer; in più, invia risposte rapide ai messaggi (solo su android); funzione disponibile quando il telefono si trova nelle vicinanze. Rilevazione continua del battito cardiaco: usa la rilevazione continua del battito cardiaco per tracciare con precisione le calorie bruciate, ottimizzare l\'allenamento e scoprire tendenze personalizzate che ti motivano a muoverti verso i tuoi obiettivi di benessere e forma fisica.', '129.99', '10', 'Smartwatch'),
	(NULL, 'Samsung Galaxy Z Flip', 'Samsung Galaxy Z Flip 5G Smartphone, Display ext. 1.1” Super AMOLED/int. 6.7” Dynamic AMOLED, 256GB, RAM 8GB, Batteria 3300mAh, 5G, Single Sim/eSim, Android 10, Grigio', 'Galaxy Z Flip 5G è il dispositivo a tutto schermo che, con il suo vetro flessbile, si piega diventando davvero tascabile; grazie ai colori eleganti e neutri ha un look premium. Galaxy Z Flip 5G è dotato di un processore potenziato in grado di soddisfare le necessità della velocità 5G; {1} scarica e guarda i tuoi film e serie TV preferiti in un attimo. Chiudi Galaxy Z Flip 5G e ti sorprenderai di quanto diventi piccolo senza perdere il suo design accattivante; comodissimo da tenere in borsa, ma anche in tasca. L’Infinity Flex Display di Galaxy Z Flip è uno schermo Dynamic AMOLED immersivo in Ultra Thin Glass con colori qualità e ridotte emissioni di luce blu; 6,7", nessun notch e cornici quasi assenti{2}. La cerniera nascosta dona un movimento preciso e fluido, permettendoti di scegliere l\'angolo di apertura; in più, una speciale tecnologia ripulente tiene lontani sporco e polvere. Rendi il tuo punto di vista ancora più unico; grazie alla tecnologia di Galaxy Z Flip puoi scattare selfie e videochiamare senza dover tenere in mano lo smartphone. Quando lo apri in modalità Flex, il tuo Galaxy Z Flip divide a metà le app e posiziona i comandi nella metà inferiore del display, trasformando quella superiore in area di visione{3}.', '936.99', '900', 'Smartphone'),
	(NULL, 'Samsung Galaxy A72', 'Samsung Galaxy A72 Smartphone, Display Infinity-O FHD+ da 6,7 pollici, 6 GB RAM e 128 GB di memoria interna espandibile, Batteria 5.000 mAh e ricarica Ultra-Rapida Black', 'Display 6,7 pollici Infinity-O: schermo con tecnologia FHD+ Super AMOLED. Splendido design: smartphone android dalle curve sottili e il design aerodinamico. L’alloggiamento ridotto della fotocamera si fonde alla perfezione con la finitura opaca, donando al telefono un look emblematico. Sistema multicamera: foto di qualità superiore grazie alla fotocamera principale da 64MP che realizza scatti chiari e nitidi. Batteria 5.000mAh¹⁶: dedica più tempo a ciò che ami grazie alla batteria di lunga durata dei telefoni cellulari Samsung, e ricaricati velocemente con 25W di ricarica Ultra-Rapida adattiva. Vivi le tue giornate all’insegna del multitasking grazie ad una potenza di elaborazione fino a 6 di RAM e a 128GB di memoria interna. Per poter utilizzare uno smartphone [Versione Italiana] in un paese extra-europeo è necessario prima effettuare almeno 5 minuti di chiamate con una sim Europea.', '385.00', '30', 'Smartphone'),
	(NULL, 'Apple Watch Series 6', 'Apple Watch Series 6 (GPS, 44 mm) Cassa in alluminio grigio siderale con Cinturino Sport nero', 'Con il modello GPS rispondi a chiamate e messaggi dall’orologio. Puoi misurare l’ossigeno nel sangue con un nuovo sensore e una nuova app. Puoi controllare il ritmo cardiaco con l’app ECG. Il display Retina always-on è 2,5 volte più luminoso alla luce del giorno, anche quando tieni abbassato il polso. Il chip S6 SiP è fino al 20% più veloce rispetto al chip dei modelli Series 5. Con Apple Watch misuri ogni giorno quanto ti muovi, e i progressi compiuti li controlli nell’app Fitness su iPhone. Puoi registrare ogni tuo allenamento: corsa, camminata, bicicletta, yoga, nuoto e ballo. Swimproof. Sincronizzi musica, podcast e audiolibri. Apple Watch richiede iPhone 6s o successivo con iOS 14 o successivo', '439.00', '50', 'Smartwatch');
